# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded wccnt 0.1 [list source [file join $dir wccntCNToscillate.tcl]]\n[list source [file join $dir wccntrj2dcd.tcl]]\n[list source [file join $dir wccntCNTbuild.tcl]]\n[list source [file join $dir wccnt.tcl]]\n[list source [file join $dir wccntMSDwater.tcl]]
